### ISSUE TITLE
这个怎么用啊

### ISSUE THREAD

**Issue by YuzukiTsuru** [cgoxopx/vomidi#1]
这个怎么用啊QwQ

**Comment by cgoxopx** [comment]
没想到还没完全开发完就有人看了。。。  
把要用来合成的音源手工切分成很多片段，保存为wav文件，然后放在同一个文件夹soundfonts里面，在里面创建一个名config文件，按照  
```
#词名 wav路径  
test test.wav
......
```
的格式写。
然后再创建一个文件notation.txt，里面按照这个格式写，作为谱子  
```
#词名 音名 强度 时间 速度  
test C5 1.0 1.0 1.0  
```
然后执行vomidi-synth soundfont notation.txt output.wav生成音频文件  
至于多音轨，导入midi文件等等，现在还没做完

**Comment by YuzukiTsuru** [comment]
R主有兴趣加入我们@GSiSY吗？我们需要这种合成器作为demo生成的QwQ

**Comment by YuzukiTsuru** [comment]
邀请已发送QwQ
